version: '3.8'

services:
  digi-assistant:
    build: .
    ports:
      - "3001:3001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PORT=3001
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped