name: digi-assistant
services:
- name: web
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: ANTHROPIC_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  http_port: 8080
  routes:
  - path: /
  build_command: npm run build:all
static_sites: []